spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=GMT&nullCatalogMeansCurrent=true
#    url: jdbc:mysql://localhost:3306/content_center
    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=UTC
    hikari:
      username: root
      password: root123456
      # connector version >= 6.x com.mysql.jdbc.Driver
      #  connector version <= 5.x  com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: content-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
#        指定集群名称
        cluster-name: BJ
        namespace: 87980947-d66c-4ee5-a8b0-3b17222c464d
        metadata:
          devlocalVersion: dev
          prodVersion: prod
          version: 1.0
server:
  port: 8010
#user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true
    clients: user-center
