spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/content_center?serverTimezone=GMT&nullCatalogMeansCurrent=true
    url: jdbc:mysql://localhost:3306/content_center
    hikari:
      username: root
      password: root123456
      # connector version >= 6.x com.mysql.jdbc.Driver
      #  connector version <= 5.x  com.mysql.cj.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: content-center
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
server:
  port: 8010